fixtures:
  repositories:
    "stdlib": "https://github.com/puppetlabs/puppetlabs-stdlib.git"
    "apt": "https://github.com/puppetlabs/puppetlabs-apt.git"
    "powershell": "https://github.com/puppetlabs/puppetlabs-powershell.git"
    "remotefile": "https://github.com/lwf/puppet-remote_file.git"
  symlinks:
    "topbeat": "#{source_dir}"
